---
title: "The Impact of Exercise on Depression and Anxiety"
author: "Abby Brown"
format: gfm
---

## Description

### Fundamental Question: 
Does regular exercise reduce symptoms of depression and anxiety in individuals diagnosed with mental health conditions?

### Hypothesis: 
Engaging in regular physical exercise leads to lower levels of depression and anxiety.

### Introduction: 
Mental health challenges are among the leading causes of workplace absenteeism and reduced productivity globally, costing businesses billions annually in lost output. Amid rising awareness of employee well-being, companies are investing in wellness programs, including fitness initiatives, with the expectation of improving employee mental health and productivity.

This study aims to explore the causal relationship between regular exercise and mental health outcomes, focusing on depression and anxiety. The findings could provide actionable insights for businesses aiming to design effective wellness programs, as well as inform policymakers about the broader benefits of promoting physical activity.


## Project Organization

- `/code` Scripts with prefixes (e.g., `01_import-data.py`, `02_clean-data.py`) and functions in `/code/src`.
- `/data` Simulated and real data, the latter not pushed.
- `/figures` PNG images and plots.
- `/output` Output from model runs, not pushed.
- `/presentations` Presentation slides.
- `/private` A catch-all folder for miscellaneous files, not pushed.
- `/writing` Reports, posts, and case studies.
- `/.venv` Hidden project library, not pushed.
- `.gitignore` Hidden Git instructions file.
- `.python-version` Hidden Python version for the reproducible environment.
- `requirements.txt` Information on the reproducible environment.

## Reproducible Environment

After cloning this repository, go to the project's terminal in Positron and run `python -m venv .venv` to create the `/.venv` project library, followed by `pip install -r requirements.txt` to install the specified library versions.

Whenever you install new libraries or decide to update the versions of libraries you use, run `pip freeze > requirements.txt` to update `requirements.txt`.

For more details on using GitHub, Quarto, etc. see [ASC Training](https://github.com/marcdotson/asc-training).
